# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 08:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Test',
            new_name='AddData',
        ),
    ]
